data_params:
  batch_size: 32
  end_date: 2007-12-31
  start_date: 1981-09-01
  test_split_size: 0.1
  train_val_shuffle: false
  val_split_size: 0.05
experiment_params:
  learning_rate: 0.0001
  manual_seed: 1337
model_params:
  dropout_probability: 0.0
  model_name: MAF
  n_blocks: 5
  n_dim: 6
  n_hidden_features: 8
  n_latent_dim: 7
  n_layers: 4
  ts_model_params:
    kwargs:
      trend_factor: 1.3
    model_name: TrendModel
  use_batch_norm: true
  use_random_masks: false
  use_random_permutations: false
  use_residual_blocks: true
  weights_model_params:
    kwargs:
      n_hidden_units: 100
    model_name: LearnableWeights
trainer_params:
  max_epochs: 50
