channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=21.3.1
- pip:
  - mlflow
  - astunparse==1.6.3
  - cloudpickle==2.2.0
  - defusedxml==0.7.1
  - denoising-diffusion-pytorch==0.31.1
  - dill==0.3.5.1
  - ipython==8.3.0
  - nflows==0.14
  - torch==1.12.1
name: mlflow-env
