model_params:
  model_name: GPR
  kernel_params:
    formula: k1 * k2
    kernels:
      - name: k1
        class_name: ConstantKernel
        kwargs:
          constant_value: 1.58
          constant_value_bounds: fixed
      - name: k2
        class_name: RBF
        kwargs:
          length_scale: 6.81
          length_scale_bounds: fixed

experiment_params:
  manual_seed: 1337

data_params:
  # index from 0 to 5
  train_dims: [0, 1, 2, 3, 4, 5]
  test_dims: [0, 1, 2, 3, 4, 5]
  start_train_date: 2008-01-01
  end_train_date: 2016-12-31
  start_test_date: 2008-01-01
  end_test_date: 2016-12-31
  train_val_equal: true
  train_permute_coords: false
  batch_size: 32

trainer_params:
  max_epochs: 0
  num_sanity_val_steps: 1
