model_params:
  model_name: MAF
  n_dim: 6
  n_latent_dim: 7
  n_layers: 4
  n_hidden_features: 32
  n_blocks: 5
  dropout_probability: 0.0
  use_batch_norm: true
  use_residual_blocks: true
  use_random_permutations: false
  use_random_masks: false
  weights_model_params:
    model_name: LearnableWeights
    kwargs:
      n_hidden_units: 100
  ts_model_params:
    model_name: TrendModel
    kwargs:
      trend_factor: 1.3

experiment_params:
  learning_rate: 0.0001
  manual_seed: 1337

data_params:
  batch_size: 32
  start_date: 1981-09-01
  end_date: 2007-12-31
  val_split_size: 0.05
  test_split_size: 0.1
  train_val_shuffle: false

trainer_params:
  max_epochs: 50
