channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=21.3.1
- pip:
  - mlflow
  - aim==3.15.1
  - astunparse==1.6.3
  - cloudpickle==2.2.0
  - colorama==0.4.6
  - denoising-diffusion-pytorch==0.31.1
  - dill==0.3.5.1
  - ipywidgets==7.6.5
  - nflows==0.14
  - scikit-learn==1.0.1
  - seaborn==0.11.2
  - statsmodels==0.13.2
  - torch==1.12.1
name: mlflow-env
